### ISSUE TITLE
`new Mapping` and `Map` do not work

### ISSUE THREAD

**Issue by milesj** [z-jxy/rpkl#18]
@z-jxy Hey 👋 

Given this config:

```pkl
codeowners {
	globalPaths = new Mapping {
		["*"] = List("@admins")
	}
	orderBy = "project-name"
	requiredApprovals = 1
	syncOnRun = true
}

constraints {
	enforceProjectTypeRelationships = true
	tagRelationships = new Mapping {
		["a"] = List("b", "c")
	}
}
```

I'd expect both the `globalPaths` and `tagRelationships` to be a record/map of key values, but they become empty values. Here's the debug output of the struct:

```
[crates/config/tests/workspace_config_test.rs:851:13] &config = WorkspaceConfig {
    schema: "https://moonrepo.dev/schemas/workspace.json",
    codeowners: CodeownersConfig {
        global_paths: {},
        order_by: ProjectName,
        required_approvals: Some(
            1,
        ),
        sync_on_run: true,
    },
    constraints: ConstraintsConfig {
        enforce_project_type_relationships: true,
        tag_relationships: {},
    },
}
```

The YAML code below works correctly. This is what I'm trying to achieve.

```yaml
codeowners:
  globalPaths:
    "*": ["@admins"]
  orderBy: "project-name"
  requiredApprovals: 1
  syncOnRun: true

constraints:
  enforceProjectTypeRelationships: true
  tagRelationships:
    a: ["b", "c"]
```

FWIW, `Listing` and `List` work, but `Mapping` and `Map` do not.
